---
- name: Create the Watchtower container
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    # Update containers every monday and thursday at 5:00 a.m.
    command: --schedule "0 0 5 * * 1,4" --cleanup
    env:
      WATCHTOWER_NOTIFICATIONS: "{{ WATCHTOWER_NOTIFICATIONS }}"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL }}"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: "{{ WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER }}"
