---
- name: Install some tools
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - htop
    - ntp
    - vim
    - git
    - curl
    - python3-pip
  notify:
    - start ntp
