---
- name: Ensures traefik dir exist
  file:
    path: "{{ traefik_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Adding traefik.toml file
  template:
    src: ../templates/traefik.toml.j2
    dest: "{{ traefik_dir }}/traefik.toml"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Adding docker-compose.yml file
  template:
    src: ../templates/docker-compose.yml.j2
    dest: "{{ traefik_dir }}/docker-compose.yml"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Create the web network
  docker_network:
    name: web

- name: Stop traefik
  shell: docker-compose down
  args:
    chdir: "{{ traefik_dir }}"

- name: Start traefik
  shell: docker-compose up -d
  args:
    chdir: "{{ traefik_dir }}"
