---
- name: Ensures traefik dir exists
  file:
    path: "{{ traefik_dir }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Ensures acme.json file exists
  file:
    path: "{{ traefik_dir }}/acme.json"
    state: touch
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: 600

- name: Adding traefik.toml file
  template:
    src: ../templates/traefik.toml.j2
    dest: "{{ traefik_dir }}/traefik.toml"
    owner: "{{ user }}"
    group: "{{ group }}"

- name: Create the web network
  docker_network:
    name: web

- name: Create the traefik container
  docker_container:
    name: traefik
    image: traefik
    restart_policy: unless-stopped
    networks:
      - name: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{ traefik_dir }}/traefik.toml:/etc/traefik/traefik.toml"
      - "{{ traefik_dir }}/acme.json:/acme.json"
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      traefik.frontend.rule: "Host:{{ traefik_api_url }}"
      traefik.docker.network: "web"
      traefik.port: "8080"
      traefik.enable: "true"
    env:
      GANDIV5_API_KEY: "{{ gandi_api_key }}"

- name: Create the Watchtower container
  docker_container:
    name: watchtower
    image: v2tec/watchtower
    restart_policy: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    # Update containers every monday at 5:00 a.m.
    command: --schedule "0 0 5 * * 1" --cleanup
    env:
      WATCHTOWER_NOTIFICATIONS: "{{ WATCHTOWER_NOTIFICATIONS }}"
      WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL: "{{ WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL }}"
      WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER: "{{ WATCHTOWER_NOTIFICATION_SLACK_IDENTIFIER }}"
